hash-format = "sha256"

[[files]]
file = "config/apotheosis/adventure.cfg"
hash = "aef751f70b9024706a9b3589dc0e1b59cb3b778c3b1055ec8f5d610ebee2ccbd"

[[files]]
file = "config/apotheosis/apotheosis.cfg"
hash = "50a75f0c3d7e52548aabc4a98634406601b72aa23a2836a9e4edbfdcebe327e2"

[[files]]
file = "config/apotheosis/enchantments.cfg"
hash = "5d8b2f12e257b81ca77b8a851f9867147e69487c882e1704d4bfb450b3780b7f"

[[files]]
file = "config/apotheosis/garden.cfg"
hash = "e63e8c6a22e733713e67b4198f361185c696171dcad9a3b5ef13471eb290fb45"

[[files]]
file = "config/apotheosis/names.cfg"
hash = "432cd149cb96778da395b91c92491ac79a1be9a5cb08abfeef6cb1e7ea8229b4"

[[files]]
file = "config/apotheosis/potion.cfg"
hash = "e611a4606eddbea9885dff9b5b20e0e2a76f3f53d0c1f0490b9304899f849ff4"

[[files]]
file = "config/apotheosis/spawner.cfg"
hash = "e138140e46eddddd9c8da330a7a26f6096ac198c376c98dfb81c597ef78c4c48"

[[files]]
file = "config/apotheosis/village.cfg"
hash = "bf6765b9abaf4b3abfb9447f9cb8bf7e85e89d46a6dafc8d290738c12e4e7947"

[[files]]
file = "config/emojiful-client.toml"
hash = "d50ffd0cefe0f14db19760302730ff44dd7836d8f5df9b3bdcd7118b1ef4457e"

[[files]]
file = "config/tconstruct-common.toml"
hash = "5fab8df842680444a7ecc8a0cd6349cef9afb30940b435dcac3cfe7073fa0733"

[[files]]
file = "config/waystones-common.toml"
hash = "485a4975ec9552f039b7c99d7748a1c68f79412048729717abec53b8c244cf43"

[[files]]
file = "mods/alexs-mobs.pw.toml"
hash = "03da06567af6005bcfd94525e773bb49b448c58b161757f8f5680b857459766c"
metafile = true

[[files]]
file = "mods/allurement.pw.toml"
hash = "2286bbe14330bfce04eacac77cab4c613b98e954ecc20c9d831da7b9636eb6b0"
metafile = true

[[files]]
file = "mods/another-furniture.pw.toml"
hash = "33a14f96c097b8593b454b4aa16f4339b40ea7b9fe767a68b5df9e9c3872f001"
metafile = true

[[files]]
file = "mods/apotheosis.pw.toml"
hash = "3b70a589cf24b5248832d89cc125f9af9a019cd86102a81c2619bb049ef1f75e"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "93824edcab0aa7a0f93f93342754f98dbc7b2526d8126b918f10805bc4e12f10"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
hash = "0ad1a046672bf487381845adea4299b77564da0b4d2072872740fffe783a512b"
metafile = true

[[files]]
file = "mods/aquaculture.pw.toml"
hash = "740db250d501ef36bfb039c22ddee10513efdecf6fc6b9253d365947ba8db880"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6d3d349f02c4ffd6a8252db88e6168f9037601660a73fd282c4203a199e9997e"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "3221c919927b9e177d138d76187442b7794fcf89c4b58af8015352f1174ea6d1"
metafile = true

[[files]]
file = "mods/atmospheric.pw.toml"
hash = "5b4554b40bd9af23e52f150047f7db3b5123d2c42f1da4b66a4d88f4fc8ed1d8"
metafile = true

[[files]]
file = "mods/ato.pw.toml"
hash = "c5795cf9270b6abed5edddff888209a3fe73f0280b1320bee7a2c04e62a710bd"
metafile = true

[[files]]
file = "mods/autoreglib.pw.toml"
hash = "4b9f680bd2c3c2efc44ce41626b2fe5860403a4ec38309ab6fd8a04bac16e8bc"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "23c80ede3b259c1c908ace792f0b95d7c6cb2155f2fcc1b3493e569b656162c2"
metafile = true

[[files]]
file = "mods/berry-good.pw.toml"
hash = "01a254b447297d79d321886a845f8299f39ae8a074a923c0495eabcd1499d071"
metafile = true

[[files]]
file = "mods/biome-music.pw.toml"
hash = "cab1f591aeef5a334befb5b314edf94b213e890fb21e890c0f68ac8afda74912"
metafile = true

[[files]]
file = "mods/biomesize.pw.toml"
hash = "1129da685c174ad4ebd18d10ffff96d714675f34b618aa586c8f0ba0dd863faa"
metafile = true

[[files]]
file = "mods/blueprint.pw.toml"
hash = "834cd67910e45c91ccc6528a40048fc4c02d1d8dc52f371fcba4891544684777"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "1d7f95592de63e85db46a17cb90c0386b9810954ae55dea2da7ba6291db0cb4d"
metafile = true

[[files]]
file = "mods/buddycards-expansions.pw.toml"
hash = "f2f890b8e404882c665a4eaca3612f86939dab59767f8e9ad66ac9e8c4a572f2"
metafile = true

[[files]]
file = "mods/buddycards.pw.toml"
hash = "8b10ffbb6bbcfb0731fa3ee2a13c0c5d87a07564d9c305091990255837e2921e"
metafile = true

[[files]]
file = "mods/building-gadgets.pw.toml"
hash = "29f7a1cfbc20432885d12c36245b503103857c068b27865d804cbd06d9b386f9"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "aaff16dd17394507e6e670b8d86ad895685c4bef4bd5a000a94569006f341252"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "3882c802ffa760a9c7581bb04bde212173edb903d54a931c5cbdf83eff6053b9"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "dbe6a9e42390a6e5fa08ebd31c44567981ec8face7afff290930d542bd87f6e7"
metafile = true

[[files]]
file = "mods/clayworks.pw.toml"
hash = "7d5a18f02ff31b2e327e718dfd00da8209716a3b93474938ac6142d6b4ecaeed"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "dd37f8dd2520e55ca2d3c85d92de682c31e4fdedea64a090bca80e1f0d3fd80a"
metafile = true

[[files]]
file = "mods/cofh-core.pw.toml"
hash = "9a56d3c04cb0669a68cfb29278d32144719d3016edb77f178286bc53d597b32e"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "14d50a18c5e9291aa077ee5c15b9113c9671d84f01ce9e1eb823741acfecae81"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "c79b4ff9b5ce619278bc4704960d4cbb78d943153f4a7560a84b000a64b2c019"
metafile = true

[[files]]
file = "mods/construction-wand.pw.toml"
hash = "504e0b21fb643f5a6e1d2db18b3975993673b7c89b062be49de37dbedc3684da"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "36217218d7336e59ae18b3b8e0acb37c9d4a432d889a1808840012b7c9d92a42"
metafile = true

[[files]]
file = "mods/creeper-overhaul.pw.toml"
hash = "938447d1a7b78c6a03b577d2f60a0fcf9ca3a5403304a9bdc201b9dbeacb89be"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "201fbdb672e83a6e12269409aae0445e14f65d2def938668269c5bcf6a2f62da"
metafile = true

[[files]]
file = "mods/ctm.pw.toml"
hash = "aaeab662940679b8ef5074189d480bd04934334bc32d29931538c8bf2d7050cd"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "3fbeebeafd2cf899a3235106343689c2e8522deb8eea32fe1bbdb28563fd57f7"
metafile = true

[[files]]
file = "mods/darker-depths.pw.toml"
hash = "ae6b9bee511edfb9e921ac2d22698245c208c66b84fd4af8946f60f152623024"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
hash = "80379f0a04b6e508313fb2ebfa1f14defc2ebcc9f3d008fbc7fd9848bdd9380a"
metafile = true

[[files]]
file = "mods/ding.pw.toml"
hash = "c2e47819fe982120f27531179a6452af78312044ad9aab609827ee008cb813c6"
metafile = true

[[files]]
file = "mods/domestication-innovation.pw.toml"
hash = "57e7276826cdbf1257221663a35be5649646d80dbb565f7e8b9d8ee2d2ccc619"
metafile = true

[[files]]
file = "mods/drp-global-datapack.pw.toml"
hash = "97625e8d9efb25abb5e32ddd744981636dd248ecf4bdfce5d3a7f42dd9ccc0e2"
metafile = true

[[files]]
file = "mods/easier-sleeping.pw.toml"
hash = "cf91d65cef2c555634892f8413667ed8ce4abd0afdc8bd1f21a08bcbbed41639"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "fadbeffdcee5f3e7a73db38e65f282acaeb57d2668d0cde928f2d1b97f41425a"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "d548b22722c1f0e1e2bf86bb5404066b4fa8259508ccd4d7a7a6615726aa15c6"
metafile = true

[[files]]
file = "mods/emojiful.pw.toml"
hash = "7c0dedfd8cccc3580dfbb68994925f97cc3ffb911de420fb56b3045f2659ba23"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "03f5a2eb3c7c2c871f8a3b3ac0235291d41e70ac4baa22e9c9140e358b8773ab"
metafile = true

[[files]]
file = "mods/enhanced-celestials.pw.toml"
hash = "6e4a34c104bf7f0754535a7738369b5da8ec28afa98fd7cfff583185da0a66ec"
metafile = true

[[files]]
file = "mods/enigmatic-graves.pw.toml"
hash = "5382640c451664e0cd7d76b7fe3087fd4f673eda86b3cd0b5758647c7752a225"
metafile = true

[[files]]
file = "mods/environmental.pw.toml"
hash = "7bfaf34655626eb4c98c5177e944783ddbde86889ace6ca27a68322bdc56366d"
metafile = true

[[files]]
file = "mods/equipment-compare.pw.toml"
hash = "5a6f56b01fec58c6737c31ff17e967ddb15a8d7959d0a25b9aa673e6981713cc"
metafile = true

[[files]]
file = "mods/every-compat.pw.toml"
hash = "7e830a3e117f5a3e6611624aacc4e12392c48c5894afed2c3427fa9ce84083db"
metafile = true

[[files]]
file = "mods/expandability.pw.toml"
hash = "2ecdf3ae76d4ad10da711a93c966f6306c1bfdec39fe9f6c356000e600bf5844"
metafile = true

[[files]]
file = "mods/farsight.pw.toml"
hash = "b8f1ed5ec382ab2fe868bb07bcef9364f3afaf17cb72afc3051842c96089b76b"
metafile = true

[[files]]
file = "mods/findme.pw.toml"
hash = "49ac4b54302b17b6df0411394d3cd336ae775df8f981d1fee961c7cb52282e32"
metafile = true

[[files]]
file = "mods/fps-reducer.pw.toml"
hash = "fd64444a5e1d1ec5c9fc4c1d015dc5c731c1f6beeaa63cf4aa359b1cd2841669"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "d407624e38c852ade10d8bf4de6949bc935d6d7a23079f5602986296c21ac1c6"
metafile = true

[[files]]
file = "mods/ftb-ultimine-forge.pw.toml"
hash = "593b46a6a0179e427679f90da1d744f2870f844628725da803f9d640023d4c77"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "e2ecdb0eaa4c2118a320126f5993f781a302d8dec01a041374d5381ed54d6a44"
metafile = true

[[files]]
file = "mods/goblin-traders.pw.toml"
hash = "ff7d3a13bf54bc26dd5bc6cf02a29c873536fb6698cded03f2be4c71f7da2b29"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "26957cccd2e46d96b644f016aac4517184a537aa09d4e433abd767c1211dac05"
metafile = true

[[files]]
file = "mods/illager-invasion.pw.toml"
hash = "4f57216f8a531b49b98406894f70f9fe635f6717f93b9c6a0c4fa9945c28e73e"
metafile = true

[[files]]
file = "mods/immersive-engineering.pw.toml"
hash = "5e817210ce0652cec8fd1b78b0b24c1a2d9b5a1f54fcd13b87aa2ec362fc7c4d"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "68b34a638042fcb11810a6266be7c1075cd39e601485f1c30c32569deb13df46"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "e6e2a7b9e445d8284a914cf067e3ee57643513f4e0a063c3fe549f432647342d"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
hash = "485e1aefa205baa57b29c54af2987257e06ef09516a32fb70759bbc700f2a337"
metafile = true

[[files]]
file = "mods/max-health-fix.pw.toml"
hash = "054652f03761f181e72924e5893a86dcdc47b752a108db873bd6b05c8ca361a8"
metafile = true

[[files]]
file = "mods/medieval-music.pw.toml"
hash = "fccbd5f635b7e5a74b8212a3fc77dff861cdcb0c1358e0ed24e1a9a9a362cc3c"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
hash = "f0684891c05b13f481c137fd14a77a41614bc37e226af07e1ad42cb85221cc90"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "ec1b184fe352b65db298ce3c93b66aa2c12a5b0a6ea1ef9a576179a1523b0264"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "93091b397f6ac25759b98be7034767689407bb344c464a9359642122a8b683db"
metafile = true

[[files]]
file = "mods/name-pain.pw.toml"
hash = "42d042ca8ddd33431d2ad1d584bde71640be6c06a0565744613fc83e31f33393"
metafile = true

[[files]]
file = "mods/neapolitan.pw.toml"
hash = "04d26d2c0bb6f78d862b5e4a4232c43cd88b5dfa182effce2fc9749c4bde8d13"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "e06240634ffc0160925d15dc99c0f6d765c04bc303fb118d76c2f6cac38eed69"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "ce7da1b0909130c1934a001903e415fe162e5044b4e01baf32a16caa13d9ce2a"
metafile = true

[[files]]
file = "mods/overweight-farming.pw.toml"
hash = "20c1dac5f4982ce5dc4b1fd188e2e21a2af01d3b81f4f8a639f23474007da4a6"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-crops.pw.toml"
hash = "17e2beb989d98c665354decdfc2ad34689278757c43514750e4f718d65e65316"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-food-core.pw.toml"
hash = "e786b40a72206eb8757d7147311eb1d83570df88e8a9048a603bc20941ac0469"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-food-extended.pw.toml"
hash = "beec8f7f650ee7afb5db43eeecf08b2a41271aeb7bb88852181726c7ab2106c8"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-trees.pw.toml"
hash = "4cb1c244f2acccb0a9842cb8f3634732ca270467ef6d8fbc9cb58faec2037f54"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "ae4c3617170709ac560c8113f1526193e79750735d12bbc2d5119f518b866799"
metafile = true

[[files]]
file = "mods/personality.pw.toml"
hash = "b5b5a25794e0e73d906b78c321293bfeb9bffc218499b194253fbc2262c71c3a"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "c8028b2468a5b5257b94d6fdd4c9bf5372ec13eef3eb40c85e6f3b808f4cdb6f"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "ea3a680ef8777698e5c14a23ce80e6972baf3f223d56de8ad503dcebbdf0b428"
metafile = true

[[files]]
file = "mods/productivebees.pw.toml"
hash = "9663ff908447fa48faf04e3c3cb3225c7ab1ef824ebdfde79ab9fe24df86b383"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "60dae26990035300fa780d675f08756ef4d5fded76423b839328d648869e6b23"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "323bf0949b42dbb97a7c35d17f436a7b2c7eb463cc97f46a54469ff3a0bad027"
metafile = true

[[files]]
file = "mods/quickstack.pw.toml"
hash = "61045df927a321354c47dee6c8bbb1adc6cea94ab05713aaeac62b9e4d328aae"
metafile = true

[[files]]
file = "mods/quickteleports.pw.toml"
hash = "d370a5dd771535b954866e947bd32960a9bdce143d2c9926c1a21fd9fe60658a"
metafile = true

[[files]]
file = "mods/regions-unexplored.pw.toml"
hash = "18abf7bf525dbb198e37c1c38fc24f5097ff9e7be5de15a1b44f02f0b9d80db9"
metafile = true

[[files]]
file = "mods/rotten-creatures.pw.toml"
hash = "de69d77d188074c508672e5f6f2d64010601a35aad7c73aebffb5dac4252b861"
metafile = true

[[files]]
file = "mods/roughly-enough-items-hacks.pw.toml"
hash = "96c189923da764902b6123f9e3ec05544966849023801b4f0e1ccca2286afaa3"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "644ccc61dbcb188c073e22e5669538883a7ec5a729ded9047083ef996e757091"
metafile = true

[[files]]
file = "mods/rubidium.pw.toml"
hash = "677339e3009ce3baf939f026be93885fe243369537dd55f3816a25c91940af17"
metafile = true

[[files]]
file = "mods/savage-and-ravage.pw.toml"
hash = "54127ed84ded9857c926c4d841d8c92b4e7d83bd02a08d0b28f60f7ccb509293"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "7cfcda9ba0dcba7d302f9ea1694e9a420b8e214b3094093d7ded6c5d4a3a6d92"
metafile = true

[[files]]
file = "mods/simple-backups.pw.toml"
hash = "bcd9c86234218573019029a85928836e655e5e058c51573d6a0a4d9bfadf8f13"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "356f9483aee50732cf162981225ea40a301099b82d570fb1ed6deadc78b16474"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "b851c35124b70292391c9b4dcdeb7205d36c7649e976909d3e1ba5a265c8fb16"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "6cf54be04d2676dd775949c2025e0f3a2019c43939ae9ddf56fb8962f5f9ab2c"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "53ace67b4c03bdccf7e31726a8055d8a80139295c57f7bf42aa113a6424df0bb"
metafile = true

[[files]]
file = "mods/spice-of-life-carrot-edition.pw.toml"
hash = "24cf95c3d275e37fc044713468c2a81918a72b8d91a8d6eee1538dff97f8139c"
metafile = true

[[files]]
file = "mods/spice-of-life-sweet-potato-edition.pw.toml"
hash = "488fd8f9e145cf0abeb23ab11ab4de5d7ca5598a6256735b02461da512151d7b"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "bbcac108eb3d98535842213f234673bb2725e8abed191c8dc5c3893a3675999a"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "526f1411f2287247b09ebe85ce4ba29daaad56f1a817d163ec194f78b11bb8ef"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "2d7fae264a11ebbdc8a3809581aa6d3b58013098a7cf73fc84aec1890ec46116"
metafile = true

[[files]]
file = "mods/thermal-cultivation.pw.toml"
hash = "93853173512757a92f560d4289d80d0b1b5835b0e0143afbb6b3485163dc5d4f"
metafile = true

[[files]]
file = "mods/thermal-dynamics.pw.toml"
hash = "7dccfa48a4ae6b036dc0e3fe517fae918d5c04b79f6c104d93206f72ce1ac40c"
metafile = true

[[files]]
file = "mods/thermal-expansion.pw.toml"
hash = "79f0f9e40bb05c2234d4603a4a7a1db3f6f8337e2210c5a804d25da29ecad7f2"
metafile = true

[[files]]
file = "mods/thermal-foundation.pw.toml"
hash = "a740b8e6a629da33df773af554a0439390b016fb42d31a71609be2954cd28668"
metafile = true

[[files]]
file = "mods/thermal-innovation.pw.toml"
hash = "1d652b97d6bf0ff4bacac7fe240ce53bde7b727e3ac00ca5c3ed5260b4a05df1"
metafile = true

[[files]]
file = "mods/thermal-integration.pw.toml"
hash = "c456c53fcd79b8cbad7c3907b48e3e1041f5af50a07cfab8238134a10dbc1cdf"
metafile = true

[[files]]
file = "mods/thermal-locomotion.pw.toml"
hash = "fc87c7cbbd6b327ce8793973f1652503cb531687a3108a918dfdd6166722e844"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
hash = "5beb03d52b7e600050191fca1694eae3d70622a3f02f9cf423bf8fcd4f5f6d26"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "d0635cf9d631f992106e0717abccdc952ba6d58036b3d316f5511bcf8257a180"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "57cd6d5b4c4dcef790611023b8feb764677289bda8cee9b0945dd44d0f3c29c7"
metafile = true

[[files]]
file = "mods/upgrade-aquatic.pw.toml"
hash = "1440950d1e69a29fd70dcce7db3aed2309883d635337184dd1ea6ee179ec2e3a"
metafile = true

[[files]]
file = "mods/village-spawn-point.pw.toml"
hash = "fbb2593d0eb714fea2aabee7e7c6755354f2c452aade86b80e7835eff6571bd6"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "7566e584dc2ba7115ce13ee79f5f15f32798f9559d3c01decace774634893159"
metafile = true

[[files]]
file = "mods/woodworks.pw.toml"
hash = "ba6df18b023abc7e096746a15f23da175bdc8ed1ec938e4285f6272264efb66e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "f8bd9594314e45e24ccb6682d9eecb944beed33adf5ce4742cc78497410a8886"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "208639b449d76824225762d3d0e831eb1821c4927272ea99ea2e69fe27a70335"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "b8a004676d00f517cd0d15e7dfbcc744dc806b3198c364735d5420255f4e525a"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "7262ea23cb8ad2519ffee135e0122a12e7bc1387fc4d938d3e16f6ea0d206011"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "799ba57de8c96266d2bec8f18ea749721394e1fdb8b4e95d90ce66a1f87cd3e1"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-forge.pw.toml"
hash = "23c78b6156a0aef262ef2964d744d50689a193a91991412b68a0da3e5c3eeaef"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "aee3398b31a60cdd05e61e3fe7fe4eea247965b2cf7a6021a43d4e0820daa1c7"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "2eae47e79517a349e5c76ab4228254d1cbebcdaeb32ee1ee69026b888caaf970"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "18509e12bcbe9da72660134894d17610b33e76c3212a107b8800e416fb94659f"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "2a06398075227d1fea776e7cc5dcce97f1242a53d7697252261f4d9c88d73a92"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "25ca73ede906cc0162479b6fefaafa3d4c79f97ccd3580cbb3df2755322c7099"
metafile = true
